Update coverage configuration

diff --git a/.github/workflows/python-test.yml b/.github/workflows/python-test.yml
--- a/.github/workflows/python-test.yml
+++ b/.github/workflows/python-test.yml
@@ -10,7 +10,7 @@ jobs:
       with:
         fetch-depth: 0
     - name: Set up Python 3.8
-      uses: actions/setup-python@v1
+      uses: actions/setup-python@v4
       with:
         python-version: 3.8
     - name: Install dependencies
@@ -28,6 +28,8 @@ jobs:
         wagtail: ["2.16", "3.0"]
     steps:
     - uses: actions/checkout@v2
+      with:
+        fetch-depth: 0
     - name: Set up Python ${{ matrix.python }}
       uses: actions/setup-python@v4
       with:
@@ -50,6 +52,8 @@ jobs:
     needs: [test]
     steps:
     - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
     - uses: actions/download-artifact@master
       with:
         name: coverage-data
@@ -62,3 +66,8 @@ jobs:
       run: python -m pip install --upgrade pip tox
     - name: Prepare Coverage report
       run: tox -e coverage-report
+    - uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'coverage.xml'
+        check_name: Python tests
